### ISSUE TITLE
Wrong order of comparison in mousePressEvent

### ISSUE THREAD

**Issue by xvallspl** [nicktrandafil/tags#7]
https://github.com/nicktrandafil/tags/blob/ca30ebcfb350cb74c4b3e70955d43ad7b9d6f983/src/tags_edit.cpp#L305

should be

```suggestion
while (it != end(impl->tags) && it->rect.top() == row) {
```

or we could access out of bounds, as we are incrementing the iterator

**Comment by nicktrandafil** [comment]
Fixed
